name: Android KMP Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-linux-android, aarch64-linux-android

    - name: Install cargo-ndk
      run: cargo install cargo-ndk

    - name: Build Rust library for Android
      run: |
        cd rust/adzuki
        cargo ndk -t x86_64 -t arm64-v8a build --release
        mkdir -p ../../kotlin/androidApp/src/main/jniLibs/{x86_64,arm64-v8a}
        cp ../target/x86_64-linux-android/release/libadzuki.so ../../kotlin/androidApp/src/main/jniLibs/x86_64/
        cp ../target/aarch64-linux-android/release/libadzuki.so ../../kotlin/androidApp/src/main/jniLibs/arm64-v8a/
        cd ../../

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: upload adk
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: kotlin/androidApp/build/outputs/apk/debug/androidApp-debug.apk

    - name: Run tests
      run: ./gradlew testDebugUnitTest
